---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-bg-route
spec:
  workspaces:
    - name: output
  params:
    - name: APPLICATION_NAME
      description: Name of the application
      type: string
    - name: WORK_DIRECTORY
      description: Directory to start build in (handle multiple branches)
      type: string
    - name: DEPLOY_ENVIRONMENT
      description: Environment to deploy the app
      type: string
    - name: TEAM_NAME
      description: Name of the team that doing this exercise :)
      type: string
    - name: VERSION
      description: Version of the application
      type: string
    - name: BG_COLOR
      description: Version of currently applied chart
      type: string
  steps:
    - name: patch-argo-conf
      workingDir: $(workspaces.output.path)/$(params.WORK_DIRECTORY)
      image: quay.io/redhat-cop/tekton-task-helm:3.6.3
      script: |
        #!/bin/sh
        yq eval -i .applications."$(params.APPLICATION_NAME)".values.selectorbglabel=\"$(params.BG_COLOR)\" "$(params.DEPLOY_ENVIRONMENT)/values.yaml"
    - name: commit-changes
      workingDir: $(workspaces.output.path)/$(params.WORK_DIRECTORY)
      image: quay.io/redhat-cop/ubi8-git:latest
      script: |
        #!/bin/sh
        # Commit the changes :P
        git config --global user.email "tekton@rht-labs.bot.com"
        git config --global user.name "🐈 Tekton 🐈"
        git config --global push.default simple
        git config --global --add safe.directory '*'
        git checkout main
        git add $(params.DEPLOY_ENVIRONMENT)/values.yaml
        git commit -m "🚀 AUTOMATED COMMIT - Deployment of $(params.APPLICATION_NAME) at version $(params.VERSION) with BG color "$(params.BG_COLOR)" 🚀" || rc=$?
        git remote set-url origin $(cat $HOME/.git-credentials)/$(params.TEAM_NAME)/tech-exercise.git
        git push -u origin main